# Generated by Django 4.2.3 on 2023-08-16 06:17
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="rprice",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
