# Generated by Django 4.0.4 on 2023-08-18 07:10
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_product_discount_percentage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="phone_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
