# Generated by Django 4.2.3 on 2023-08-14 12:03
from __future__ import annotations

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0002_coupon_is_used"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupon",
            name="is_used",
        ),
        migrations.AddField(
            model_name="coupon",
            name="redeemed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
